// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';
import {context} from '../models';

export function Connect(arg1:string):Promise<services.Response>;

export function CreateConnection(arg1:models.ConnectionRequest):Promise<services.Response>;

export function DeleteConnection(arg1:string):Promise<services.Response>;

export function Disconnect(arg1:string):Promise<services.Response>;

export function IsConnected(arg1:string):Promise<services.Response>;

export function ListConnections():Promise<services.Response>;

export function SetContext(arg1:context.Context):Promise<void>;

export function TestConnection(arg1:models.ConnectionRequest):Promise<services.Response>;

export function UpdateConnection(arg1:string,arg2:models.ConnectionRequest):Promise<services.Response>;
