// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['services']['ConnectionService']['Connect'](arg1);
}

export function CreateConnection(arg1) {
  return window['go']['services']['ConnectionService']['CreateConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['services']['ConnectionService']['DeleteConnection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['services']['ConnectionService']['Disconnect'](arg1);
}

export function IsConnected(arg1) {
  return window['go']['services']['ConnectionService']['IsConnected'](arg1);
}

export function ListConnections() {
  return window['go']['services']['ConnectionService']['ListConnections']();
}

export function SetContext(arg1) {
  return window['go']['services']['ConnectionService']['SetContext'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['services']['ConnectionService']['TestConnection'](arg1);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['services']['ConnectionService']['UpdateConnection'](arg1, arg2);
}
