// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloneDatabase(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ExplorerService']['CloneDatabase'](arg1, arg2, arg3, arg4);
}

export function DropDatabase(arg1, arg2, arg3) {
  return window['go']['services']['ExplorerService']['DropDatabase'](arg1, arg2, arg3);
}

export function DropTable(arg1, arg2, arg3) {
  return window['go']['services']['ExplorerService']['DropTable'](arg1, arg2, arg3);
}

export function GetColumns(arg1, arg2, arg3) {
  return window['go']['services']['ExplorerService']['GetColumns'](arg1, arg2, arg3);
}

export function GetDatabases(arg1) {
  return window['go']['services']['ExplorerService']['GetDatabases'](arg1);
}

export function GetIndexes(arg1, arg2, arg3) {
  return window['go']['services']['ExplorerService']['GetIndexes'](arg1, arg2, arg3);
}

export function GetSchemaTree(arg1) {
  return window['go']['services']['ExplorerService']['GetSchemaTree'](arg1);
}

export function GetTableDDL(arg1, arg2, arg3) {
  return window['go']['services']['ExplorerService']['GetTableDDL'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['services']['ExplorerService']['GetTables'](arg1, arg2);
}

export function SearchTables(arg1, arg2, arg3) {
  return window['go']['services']['ExplorerService']['SearchTables'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['services']['ExplorerService']['SetContext'](arg1);
}

export function TruncateTable(arg1, arg2, arg3) {
  return window['go']['services']['ExplorerService']['TruncateTable'](arg1, arg2, arg3);
}
