// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CloneDatabase(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<services.Response>;

export function DropDatabase(arg1:string,arg2:string,arg3:string):Promise<services.Response>;

export function DropTable(arg1:string,arg2:string,arg3:string):Promise<services.Response>;

export function GetColumns(arg1:string,arg2:string,arg3:string):Promise<services.Response>;

export function GetDatabases(arg1:string):Promise<services.Response>;

export function GetIndexes(arg1:string,arg2:string,arg3:string):Promise<services.Response>;

export function GetSchemaTree(arg1:string):Promise<services.Response>;

export function GetTableDDL(arg1:string,arg2:string,arg3:string):Promise<services.Response>;

export function GetTables(arg1:string,arg2:string):Promise<services.Response>;

export function SearchTables(arg1:string,arg2:string,arg3:string):Promise<services.Response>;

export function SetContext(arg1:context.Context):Promise<void>;

export function TruncateTable(arg1:string,arg2:string,arg3:string):Promise<services.Response>;
