// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function SaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<services.Response>;

export function SetContext(arg1:context.Context):Promise<void>;
