// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchUpdate(arg1) {
  return window['go']['services']['QueryService']['BatchUpdate'](arg1);
}

export function DeleteRow(arg1) {
  return window['go']['services']['QueryService']['DeleteRow'](arg1);
}

export function Execute(arg1) {
  return window['go']['services']['QueryService']['Execute'](arg1);
}

export function ExecuteRaw(arg1, arg2, arg3) {
  return window['go']['services']['QueryService']['ExecuteRaw'](arg1, arg2, arg3);
}

export function InsertRow(arg1) {
  return window['go']['services']['QueryService']['InsertRow'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['QueryService']['SetContext'](arg1);
}

export function UpdateRow(arg1) {
  return window['go']['services']['QueryService']['UpdateRow'](arg1);
}
