// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {context} from '../models';

export function BatchUpdate(arg1:models.BatchUpdateRequest):Promise<services.Response>;

export function DeleteRow(arg1:models.DeleteRowRequest):Promise<services.Response>;

export function Execute(arg1:models.QueryRequest):Promise<services.Response>;

export function ExecuteRaw(arg1:string,arg2:string,arg3:string):Promise<services.Response>;

export function InsertRow(arg1:models.InsertRowRequest):Promise<services.Response>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateRow(arg1:models.UpdateRowRequest):Promise<services.Response>;
